name: Deployment

on:
  release:
    types:
      - created

jobs:
  release_linux:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - run: |
          shards build --production --release --static --no-debug
          strip ./bin/*
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/'
        with:
          files: |
            ./bin/*
